import samsungPic from 'assets/images/samsung.png';

export const DATA = [
  {
    id: 1,
    cardName: '개발자 e*lancer team',
    img: samsungPic,
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 2,
    cardName: '리액트 개발자 e*lancer team',
    freelancer: '조*혁 | 15년 경력 개발자',
    title: '성장하는 개발자 조*혁입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 3,
    cardName: '풀스택 개발자',
    freelancer: '심*무 | 20년 경력 개발자',
    title: '성장하는 개발자 심*무입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 4,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 5,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 6,
    cardName: '개발자 e*lancer team',
    img: samsungPic,
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 7,
    cardName: '개발자 e*lancer team',
    img: samsungPic,
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 8,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 9,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 10,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 11,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 12,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
  {
    id: 13,
    cardName: '개발자 e*lancer team',
    freelancer: '김*현 | 10년 경력 개발자',
    title: '성장하는 개발자 김*현입니다.',
    stack: [
      'Front-end',
      'Back-end',
      'Java',
      'Spring',
      'React',
      'JavaScript',
      'Postgresql',
      'Angular',
      'C#',
      'Flutter',
      'Docker',
    ],
    description:
      '수행 프로젝트 : SK ONS E-HR 인사평가 시스템 고도화, 그린재킷 캐디 피 카드결제 앱, 다날 선불중게 플랫폼, 롯데시네마 VOD 서비스, COMPAS도시문제해결플랫폼',
    ReviewRate: '★ 5.0',
    ReviewTotal: '(조회수 1904)',
  },
];
